[project]
name = "nlp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair<5",
    "pandas>=3.0.1",
    "fastapi",
    "langchain",
    "langchain-community",
    "langchain-huggingface",
    "langchain-text-splitters",
    "langchain-chroma",
    "chromadb",
    "requests",
    "sentence-transformers",
    "streamlit",
    "torch",
    "transformers",
    "accelerate",
    "bitsandbytes",
    "peft",
    "datasets",
    "trl",
    "pythainlp",
    "uvicorn",
]

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
